name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: "14"
      - name: Prepare
        run: npm ci
      - name: Build
        run: npm run build
      - name: Type check
        run: npm run test:typecheck
      - name: Test
        run: npm run codecov -- -t ${{ secrets.CODECOV_KEY }}
      - name: Lint
        run: npm run lint
