name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.36.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build
        npm run lint
      test-commands: npm test
      report-coverage: true
      coverage-file: ./coverage/lcov.info
