name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-nodejs.yml@0.33.3
    with:
      node-version: 16
      version: ${{ github.event.inputs.version }}
      build-commands: |
        npm ci
        npm run build
        npm run build:docs
        npm test
      artifact-path: dist/
      npm: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      npm-token: ${{ secrets.NPM_TOKEN }}

  deploy-docs:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: deploy-docs
          ref: main
          token: ${{ secrets.REPO_ACCESS }}

